### ISSUE TITLE
Bug again... with Get_data.smk

### ISSUE THREAD

**Issue by hypaik** [hemberg-lab/MicroExonator#28]
Dear developer

There are a lot issues that I can't solve again... 

Here is the error message I've got:
 snakemake -s MicroExonator.smk --cluster-config cluster.json --cluster "sbatch --cpus-per-task {cluster.cpus} -p {cluster.p} --output {cluster.output} --error {cluster.error} --mem {cluster.mem}" --use-conda -k -j 50 -np
Building DAG of jobs...
MissingInputException in line 16 of /home/hyojung/srcGit/MicroExonator2/MicroExonator/rules/Get_data.smk:
Missing input files for rule download_fastq:
download/round2/Murine_cortex:CamK_D_1.download.sh

I tried dry-run of MicroExonator before the long list of local files. But something wrong.
Yes, I also tried a different version of config.yaml, like Optimize_hard_drive: T/F as well.

Thank you.

**Comment by hypaik** [comment]
Hi, 
I found that the new version "Get_data_smk" is wrong for my cluster. Because I simply switched it by the previous Get_data file, then the MicroExonator works for me.

However, I can't sure it only happens in my cluster environment.
But I think it would be shared for other users.

My cluster uses SLURM. So I changed 'cluster.json' for me.
Here is the cluster.json for SLURM.
{
    "__default__" :
    {
        "J"     : "microexonator",
        "cpus"     : "1",
        "p"     : "all",
        "mem"    : 10000,
        "output"    : "microexonator.%j.out",
        "error"     : "microexonator.%j.err"
    },  

.... other parts are the same with the original one.

Thank you.

**Comment by geparada** [comment]
Hello,

This issue is a bit confusing, but I will try to help. First of all, if you disable `Optimize_hard_drive` by setting it as F or deleting it from the config file, you should not have the following error:

Missing input files for rule download_fastq:
download/round2/Murine_cortex:CamK_D_1.download.sh

Can you please confirm this?

In order to run MicroExonator cluster.json must be configured according to your queuing system. Can you please let me know if you manage to run MicroExonator in your cluster. If you did, it would really appreciate if you can share the cluster.json so we can include this file at the example folder. 

Thanks,
Guillermo

**Comment by hypaik** [comment]
Hi, I'm back.

With my post-doc, I've tested several things with the source code. There are a lot of error messages (Too many and I need time to figure it out). 
In summary, most of them are related to an absence of temp files, and the snakemake can't go to the next step. So, my post-doc changed the code. 

We removed some lines (the deletion of temp files), and our code kept all of the temp files. Then, we finally get the report file.
Of course, we also tried the recommended option for 'Otimize_hard_drive: F', but it doesn't work for us. The source code spits out the error messages by the absence of temp files for the next calculation. 

Thus, I think this problem would be related to our cluster queuing system. Because the original version of Microexonator is based on the lsf. But our cluster uses SLURM.  If you don't mind, can I send a source code we changed? I think for the use of Microexonator under SLURM, other users should know this issue. And hopefully, you can update Microexonator for other users who use SLURM. 

Let me know it is ok that I send our code for the correspondence of the paper of MicroExonator (I know your paper was published at Genome Biology, Congrats).

**Comment by geparada** [comment]
Hello there,

Thanks for your message, I am glad you are back into this.

The issues you are referring to related to temporary files are only encountered if in some situations when you try to resume your run after changing the configuration file. I suggest you try with a fresh run or manually delete protected files (`Round1/*.row_ME.filter1`and `Round2/*.filter1.ME_SJ_coverage`) before running MicroExonator again. Moreover, I would like to remind you that MicroExonator is based on Snakemake (not lsf), therefore checking up snakemake documentation could be useful for you. For example in the command line [documentation](https://snakemake.readthedocs.io/en/stable/executing/cli.html) you can see that there is an option that is called `--notemp`, so if you want to avoid the removal of temporary files you don't really need to modify MicroExonator's code, but just use the `--notemp` flag when you execute snakemake. This could be useful to do while you still manage to

Snakemake can be configured to work with different schedulers, in our cluster we use lsf so that is the only cluster.yaml file that we have tried so far. So, again, is not like we developed MicroExonator only for lsf users... we just provided an example how to configure snakemake to run with lsf, because that is the scheduler we are using in our cluster. I know that other groups have managed to run MicroExonator work with SLURM without any problems. 

To figure out how to configure snakemake coordinate the job submission with SLURM, I recommend you to check the cluster configuration section on snakemake [documentation](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html), as they provide examples of using a config.yaml file for SLURM and LSF. I think this documentation can enable you to easily adapt the config.yaml file we provide as an example to your own needs with SLURM. As I am not using any SLURM computer cluster I cannot try it myself, but if you want more close assistance to overcome this you could contact me through email. It would be indeed very useful of other users if we provide config.yaml files to work under different systems, but for this, I need contribution from users like you who are running MicroExonator under different schedulers. Thus, If you manage to get a cluster.yaml file working for SLURM I would appreciate if you can share it with us, so we could upload it to this repository and help other users.

Regarding the correspondence of the paper, you are more than welcome to send an email to the corresponding authors. But I think if you contact me instead, then I can give you more direct assistance. 

Best,
Guillermo
