### ISSUE TITLE
local_samples.tsv - specify multiple FASTQs (paired-end reads) in 'path' column? 

### ISSUE THREAD

**Issue by SamBryce-Smith** [hemberg-lab/MicroExonator#4]
Hi,

Thanks for providing the tool, looks very promising. I have a question about configuring the local_samples.tsv file when inputting local FASTQ files. 

In your example [local_samples.tsv](https://github.com/hemberg-lab/MicroExonator/blob/master/Examples/Runs/COSMIC/local_samples.tsv) file, there is just one FASTQ file specified for each sample. The samples I want to run have paired end reads in separate files. Can MicroExonator handle paired end reads in separate files, or do I need to provide interleaved FASTQ files?

I've had a peek at init.skm (lines 59-85), and by the looks of it only one FASTQ file can be provided per row, but I would really appreciate any clarification you can give.

Thanks for your time and all the best,
Sam

**Comment by geparada** [comment]
Hello Sam!

Thanks for your interest, as you well observed at the moment I have not integrated a specific option for paired-end reads. I will try to work on that after we officially release the tool. However, it is still possible to generate individual counts for each pair by separate and then you can just sum the counts that correspond to a single paired-end sample. I definitely think it would nicer to integrate an option for paired-end since it may improve the discovery of microexons, so I will have it on my to-do list. 

Best,
Guillermo

**Comment by SamBryce-Smith** [comment]
Hi Guillermo,

Thanks for the clarification and apologies for the delayed response. To echo your thoughts it would be great to be able to integrate paired end reads when you have the time. In my case, the samples I'm testing were generated with 100 bp reads, so I suspect that will be more than sufficient for discovery even just using one of the read pairs. 

Thanks for the suggestion RE running separately on each read pair, I will give that a go. If it's ok with you I may return to this issue for feedback on the specifics, as I think it would be nice for any future users to be aware of the current limitation & best way to approach this.

All the best,
Sam

**Comment by SamBryce-Smith** [comment]
Hi Guillermo,


Apologies for another late follow-up. I've been thinking about how this could be implemented and I think it's more straightforward than I first thought, but I'd appreciate your thoughts and advice.


I personally can't see any benefit to aligning paired end reads in paired end alignment mode for the detection of microexons with your approach. It could even be very detrimental in some cases - I see bowtie requires a maximum insert size parameter in paired end mode for which valid alignments of both mates have to satisfy. However, given the size of the custom SJ reference tags, I suspect it would be very unlikely for read pairs to align to the same reference. Assuming that bowtie would have no way to calculate insert size if read mates aligned to different references, I suspect they would not be considered valid, and you would be losing 'microexon reads' (I should test this assumption though...).


If I could generalise my understanding of what MicroExonator is trying to do with the various alignment steps, I'd say it's essentially trying to identify splice junction spanning reads (that either contain a microexon or do not). So even for the 'validation steps' - e.g. *bowtie_to_genome* to check whether the putative microexon read has a primary ungapped alignment to genome - I can't see information about the ME_read's mate alignment being beneficial for validating the ME_read either. From my intuition, it's possible the mate could too span a splice junction and not get a ungapped primary alignment with bowtie, so knowing whether the mate also aligns to the genome or not does not provide additional unambiguous support for the validity of the ME_read.


Anyway bit of long ramble that ends with a hacky suggestion to support paired-end reads. **Could I just concatenate the FASTQs files for a given sample and input them to MicroExonator, such that aligners consider & align them as if they were a single-end sample?** If you were considering something along those lines, I am happy to give it a go and submit a pull request - speaking from a user's perspective automatic handling of paired-end read files would be a welcome enhancement for ease of use and reproducibility of the tool.


Thanks again for your time (and once again for providing the tool, preliminarily the data obtained seems exciting!). If you are happy to share your thoughts on how you were planning to support paired-end reads I would very much appreciate it. I hope you can follow my train of thought here, and again I may have missed something on the benefits/pitfalls of running aligners in paired end alignment mode when it comes to detecting microexons, so I would be very keen to pick your brain about this. 

All the best,
Sam

**Comment by geparada** [comment]
Hello Sam,
Now that we finally publish this I feel way more relief to start addressing each of the points that have been made here. We have now generated additional documentation and guidelines, which we soon going to make available. Before publishing our manuscript I was trying different approaches that have made the pipeline more efficient and versatile for different purposes, so there has been quite a development.  


**What is the current state of this?**

I basically implemented a .tsv input where you can declare your paired-end reads in case you input fastq.gz files. Automatically merge the pairs during the quantification (similarly to what you have suggested). If you rather use SRA codes to input MicroExonator, the generated scripts at the `download` folder are able to determine if the reads are single or paired-end. If the SRA data is paired-end, they are automatically merged from the beginning. So now, what you have suggested it's all handled automatically.

Please get in touch by email if you want to follow up this issue. I think now it is pretty solved, but you are more than welcome to contribute if you still think there is something missing. I will try to update the online documentation soon, but still this year we are planning to publish some extra guidelines to improve the user experience.

I am still in doubt of whether further develop MicroExonator to enable BWA, HISAT2 and bowtie to map as paired-end. Since MicroExonator maps to a library of splice junctions, I think we might not gain too much by doing this. In fact, as you pointed out, it could be even detrimental to do this! I have to admit I am impressed by how well you understood the pipeline. I am sorry for the long time gap before my answer. 

All the best,
Guillermo

**Comment by SamBryce-Smith** [comment]
Hi Guillermo,

No problem at all with the delay, I can imagine it has been a busy time with corrections and updates etc. Thanks for updating me too on your changes. I must admit I've got sidetracked by my main project and needed the reminder to come back to microexons!

> I basically implemented a .tsv input where you can declare your paired-end reads in case you input fastq.gz files. Automatically merge the pairs during the quantification (similarly to what you have suggested). If you rather use SRA codes to input MicroExonator, the generated scripts at the download folder are able to determine if the reads are single or paired-end. If the SRA data is paired-end, they are automatically merged from the beginning. So now, what you have suggested it's all handled automatically

That's awesome. Thanks for putting the time in, whatever I would have ended up doing would have been much choppier. 


> I am still in doubt of whether further develop MicroExonator to enable BWA, HISAT2 and bowtie to map as paired-end. Since MicroExonator maps to a library of splice junctions, I think we might not gain too much by doing this. In fact, as you pointed out, it could be even detrimental to do this! I have to admit I am impressed by how well you understood the pipeline. I am sorry for the long time gap before my answer.

As you say I don't really have anything further to suggest on this front, the biggest improvement I could see from doing this was just to potentially increase the read count and help discover some more lowly expressed/included microexons. Thanks for the kind comment too, but you should take some of the credit for that. Your pipeline was pretty well explained in the pre-print, and putting everything together in Snakemake made it easy for me to play with it and fill in the gaps. 

I'll let you know if I have any other questions/user suggestions. Thanks again for keeping me in the loop and for sharing your good work :)

Congrats on the getting the paper accepted too, I'll have to check out the finished product!

Cheers,
Sam

**Comment by geparada** [comment]
Great to read your reply Sam!

We are soon going to release a protocol chapter for a book, where we describe in more detail all the available functions of MicroExonator. If you are interested to re-take the analyses with MicroExonator, you can drop me an email and I can send you the draft of this chapter. This might enable you to quickly catch up with all the specifications.

All the best,
Guillermo
