### ISSUE TITLE
error "MissingInputException" and "Missing input files for rule GetPWM"

### ISSUE THREAD

**Issue by binasu** [hemberg-lab/MicroExonator#6]
Hi,

Genome_fasta : ~/MicroExonator/c_elegans.PRJNA13758.WS276.genomic.fa
Gene_anontation_bed12 : ~/MicroExonator/Caenorhabditis_elegans.WBcel235.bed12
GT_AG_U2_5 : NA
GT_AG_U2_3 : NA
conservation_bigwig : ~/MicroExonator/ce11.phyloP26way.bw
working_directory : ~/MicroExonator/
ME_DB : ~/MicroExonator/Cel
ME_len : 27
Optimize_hard_drive : T
min_number_files_detected: 2

And a design.tsv file

path	sample
/scratch/xx.fastq	xx
/scratch/yy.fastq	yy

And then did a dry-run:
snakemake -s MicroExonator.skm --cluster-config config.yaml --use-conda -k -np

But I'm getting the error:

Building DAG of jobs...
MissingInputException in line 42 of /gpfs/fs1/home/j/jcalarco/bsugumar/MicroExonator/rules/Get_data.skm:
Missing input files for rule GetPWM:
~/MicroExonator/Caenorhabditis_elegans.WBcel235.bed12
~/MicroExonator/c_elegans.PRJNA13758.WS276.genomic.fa

Thanks for your help!

Bina

**Comment by geparada** [comment]
Hello Bina,

Now that our work is finally published online, I am taking more care of the issues that have been reported here. Sorry, I took me so long to get back to you. I think this error is because you are not using the full path, I should definitely advise against using relative path characters such as `~` or `..`.  I will take a note to warn about this in our documentation.

During the last period, I have developed several aspects of MicroExonator. So please do get in touch (by email) if you are interested to catch up with some updates. I will anyway update the documentation soon. 

Best,
Guillermo
